ARG PG_VERSION=15
ARG PGRX_VERSION=0.9.8

FROM quay.io/coredb/pgrx-builder:pg${PG_VERSION}-pgrx${PGRX_VERSION}

WORKDIR /app

COPY --chown=postgres:postgres . .

ARG EXTENSION_NAME
ARG EXTENSION_VERSION

RUN cd extension && cargo pgrx package