ARG PG_VERSION=15
ARG PGRX_VERSION=0.8.4

FROM quay.io/coredb/pgrx-builder:pg${PG_VERSION}-pgrx${PGRX_VERSION}

ARG PG_VERSION=15
ARG PGRX_VERSION=0.8.2

WORKDIR /app

COPY --chown=postgres:postgres . .

ARG EXTENSION_NAME
ARG EXTENSION_VERSION

RUN cd extension && cargo pgrx package